# Generated by Django 4.0.2 on 2022-02-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_books_book_rename_shelves_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='reading',
            field=models.BooleanField(default=False),
        ),
    ]
