# Generated by Django 4.0.2 on 2022-02-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn10',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn13',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='selflink',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
