# Generated by Django 4.0.2 on 2022-03-08 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_book_shelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='main.shelf'),
        ),
    ]
